---
title: "Exploring the other files"
output:
  html_document:
    df_print: paged
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_dir = "docs") })
---

> This is just exploratory, using 1q2018 data and some test extractions.


```{r setup, echo=T, results='hide', message=F, warning=F}
library(tidyverse)
```

## Import base 2

```{r}
base2 <- read_tsv(
  "data-test/PUDF_base2_1q2018_test.txt",
    col_types = cols(.default = col_character())
) %>% 
  select(-X100) %>% 
  mutate_at(
    vars(contains("_AMOUNT")), as.numeric
  )

base2 %>% glimpse()
```

## Import charges

> Uses test data

Removes the last empty column and converts some fields to numeric.

```{r}
charges <- read_tsv(
  "data-test/test_charges_1q2018.txt",
  col_types = cols(.default = col_character())
) %>%
  select(-X14) %>% 
  mutate_at(
    vars(starts_with("CHRGS_")), as.numeric
  ) %>% 
  mutate_at(vars(
      UNITS_OF_SERVICE,
      UNIT_RATE
    ),
    as.numeric
  )

charges %>% glimpse()
```


## Import facilities

This pulls from the raw Facility file for 1q2018.

```{r}

facility <- read_tsv(
  "data-raw/PUDF 1Q2018 tab-delimited/Facility_type1q2018_tab.txt",
  col_types = cols(.default = col_character())
) %>%
  select(-X13)

facility %>% glimpse()
```
